# ============================================================================
# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/smart-attendance-system
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Flyway
spring.flyway.url=jdbc:postgresql://localhost:5432/smart-attendance-system
spring.flyway.user=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/postgre

# JPA
spring.jpa.hibernate.ddl-auto=update

# Port
server.port=8083
