# ============================================================================
# Local Profile - PostgreSQL محلي (Development)
# شغّل البرنامج بـ: --spring.profiles.active=local
# تأكد إن PostgreSQL مشتغل على localhost:5432
# ============================================================================

# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/smart-attendance-system
spring.datasource.username=postgres
#spring.datasource.password=admin123456789

# Flyway
spring.flyway.url=jdbc:postgresql://localhost:5432/smart-attendance-system
spring.flyway.user=postgres
#spring.flyway.password=admin123456789
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/postgre

# JPA
spring.jpa.hibernate.ddl-auto=update

# Port
server.port=8083